# Generated by Django 4.0.6 on 2022-07-19 21:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNum', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('role', models.BooleanField()),
            ],
        ),
    ]
