# Generated by Django 4.0.6 on 2022-07-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phoneNum',
            field=models.CharField(max_length=255),
        ),
    ]
