# Generated by Django 4.0.6 on 2022-07-21 18:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0002_alter_teammember_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phoneNum',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
