# Generated by Django 4.0.6 on 2022-07-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0005_alter_teammember_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='phoneNum',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('r', "Regular - Can't delete members"), ('a', 'Admin - Can delete members')], default='r', max_length=1),
        ),
    ]
