# Generated by Django 4.0.6 on 2022-07-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0006_alter_teammember_email_alter_teammember_phonenum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
